### ISSUE TITLE
Modrinth/CurseForge upload

### ISSUE THREAD

**Issue by RaptaG** [roro1506HD/fabric-custom-sky#3]

**Comment by roro1506HD** [comment]
I originally made this mod for a friend (thus not being uploaded to any mods websites) and Github releases were more than enough for that usage. I will consider uploading it to these two websites

**Comment by Uranite** [comment]
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/355#issuecomment-1144675686

**Comment by RaptaG** [comment]
> https://github.com/Fabulously-Optimized/fabulously-optimized/issues/355#issuecomment-1144675686

Yes I was about to close these issue since this mod is essentially illegal. I'm really sad though because it would be cool to have it.
